# Generated by Django 4.2.3 on 2023-07-19 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_status_options_remove_status_status_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Language',
            new_name='Tag',
        ),
    ]
