# Generated by Django 4.2.3 on 2023-07-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='preview',
            field=models.ImageField(default=None, upload_to='D:\\Benutzer\\Documents\\GitHub\\timeofjustice.eu\\timeofjustice\\api/static/images/'),
            preserve_default=False,
        ),
    ]
