# Generated by Django 4.2.3 on 2023-07-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_project_git'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('index',)},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-name',)},
        ),
        migrations.AddField(
            model_name='image',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
