# Generated by Django 4.2.3 on 2023-07-20 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_cell_x_cell_y'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cell',
            unique_together={('x', 'y')},
        ),
    ]
