# Generated by Django 4.2.3 on 2023-07-20 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_cell_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cell',
            unique_together=set(),
        ),
    ]
