# Generated by Django 4.2.3 on 2023-07-26 18:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_placetimeout_id_alter_placetimeout_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='last_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
