# Generated by Django 4.2.3 on 2023-07-26 19:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_cell_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastplaced',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
