# Generated by Django 4.2.3 on 2023-07-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_lastplaced_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Overlay',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OverlayImage',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='C:/xampp/htdocs/timeofjustice.eu/timeofjustice/static/data/images/')),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=50)),
                ('height', models.IntegerField(default=50)),
            ],
        ),
    ]
