# Generated by Django 4.2.3 on 2023-07-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_alter_tiles_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiles',
            name='delta_update',
            field=models.IntegerField(default=0),
        ),
    ]
