# Generated by Django 4.2.3 on 2023-07-31 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_alter_overlay_options_alter_overlayimage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tile',
            options={'ordering': ('x', 'y'), 'verbose_name': '  Tile', 'verbose_name_plural': '  Tiles'},
        ),
        migrations.AddField(
            model_name='overlayimage',
            name='layout',
            field=models.ImageField(editable=False, max_length=255, null=True, upload_to=''),
        ),
    ]
