# Generated by Django 5.1.2 on 2025-06-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('room', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
    ]
