# Generated by Django 5.1.2 on 2025-06-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('r_place', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('color', models.CharField(max_length=7)),
                ('last_modified', models.DateTimeField(editable=False)),
            ],
            options={
                'verbose_name': '  Cell',
                'verbose_name_plural': '  Cells',
                'ordering': ('-last_modified', 'x', 'y'),
            },
        ),
    ]
