# Generated by Django 5.1.2 on 2025-06-13 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('r_place', '0002_cell'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
