# Generated by Django 5.1.2 on 2025-06-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('r_place', '0003_delete_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Canvas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('width', models.IntegerField(default=1000)),
                ('height', models.IntegerField(default=1000)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Canvas',
                'verbose_name_plural': 'Canvases',
            },
        ),
    ]
