# Generated by Django 5.1.2 on 2025-06-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('r_place', '0004_canvas'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvas',
            name='name',
            field=models.CharField(default='Default Canvas', max_length=100, unique=True),
        ),
    ]
