# Generated by Django 5.1.2 on 2025-08-03 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('r_place', '0006_cell_canvas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='canvas',
            options={'ordering': ('-active', 'id'), 'verbose_name': 'Canvas', 'verbose_name_plural': 'Canvases'},
        ),
    ]
