# Generated by Django 5.1.2 on 2025-08-23 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('r_place', '0007_alter_canvas_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenderedCanvas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('image_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('canvas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendered_canvases', to='r_place.canvas')),
            ],
            options={
                'verbose_name': 'Rendered Canvas',
                'verbose_name_plural': 'Rendered Canvases',
                'ordering': ('-created_at',),
            },
        ),
    ]
