# Generated by Django 6.0 on 2026-08-19 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0014_avatar_wallet_avatar"),
        ("r_place", "0008_renderedcanvas"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="canvas",
            options={"ordering": ("-name",), "verbose_name": "Canvas", "verbose_name_plural": "Canvases"},
        ),
        migrations.AddField(
            model_name="cell",
            name="wallet",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="cells", to="games.wallet"),
        ),
    ]
