# Generated by Django 6.0 on 2026-01-09 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('r_place', '0008_renderedcanvas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='canvas',
            options={'ordering': ('-name',), 'verbose_name': 'Canvas', 'verbose_name_plural': 'Canvases'},
        ),
    ]
