services:
  db:
    image: postgres:17
    profiles: ["production", "dev"]
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    image: redis:latest
    profiles: ["production", "dev"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    env_file:
      - .env

  django-web:
    build: .
    container_name: django-docker
    profiles: ["production"]
    ports:
      - "8001:8001"
    depends_on:
      - db
      - redis
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}

      DEBUG: ${DEBUG}
      LOCAL_PRODUCTION: ${LOCAL_PRODUCTION}
      IS_STABLE: ${IS_STABLE}

      DJANGO_LOGLEVEL: ${DJANGO_LOGLEVEL}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}

      FILE_DESTINATION: ${FILE_DESTINATION}
      LOGGING_DESTINATION: ${LOGGING_DESTINATION}
      ADMIN_URL: ${ADMIN_URL}

      USE_OTP: ${USE_OTP}

      DATABASE_ENGINE: ${DATABASE_ENGINE}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
    env_file:
      - .env
    volumes:
      - static_volume:/app/backend/staticfiles
      - files_volume:/app/backend/files

  nginx:
    build: .nginx
    profiles: ["production"]
    ports:
      - "8000:80"
    depends_on:
      - django-web
    volumes:
      - static_volume:/app/backend/staticfiles
      - files_volume:/app/backend/files

  django-web-dev:
    build: dockerfile.dev
    container_name: django-docker-dev
    profiles: ["dev"]
    ports:
      - "8001:8001"
    depends_on:
      - db
      - redis
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}

      DEBUG: ${DEBUG}
      LOCAL_PRODUCTION: ${LOCAL_PRODUCTION}
      IS_STABLE: ${IS_STABLE}

      DJANGO_LOGLEVEL: ${DJANGO_LOGLEVEL}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}

      FILE_DESTINATION: ${FILE_DESTINATION}
      LOGGING_DESTINATION: ${LOGGING_DESTINATION}
      ADMIN_URL: ${ADMIN_URL}

      USE_OTP: ${USE_OTP}

      DATABASE_ENGINE: ${DATABASE_ENGINE}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
    env_file:
      - .env
    volumes:
      - static_volume:/app/backend/staticfiles
      - files_volume:/app/backend/files
      - ./backend:/app/backend
      - ./frontend:/app/frontend

  nginx-dev:
    build: .nginx-dev
    profiles: ["dev"]
    ports:
      - "80:80"
    depends_on:
      - django-web-dev
    volumes:
      - static_volume:/app/backend/staticfiles
      - files_volume:/app/backend/files
volumes:
  postgres_data:
  static_volume:
  files_volume:
  redis_data: