# Generated by Django 5.1.2 on 2025-06-03 13:31

from django.db import migrations


sql_query = (
    "UPDATE django_content_type SET app_label='games' WHERE app_label='games';"
    "ALTER TABLE casino_wallet RENAME TO games_wallet;"
    "ALTER TABLE casino_vault RENAME TO games_vault;"
    "UPDATE django_migrations SET app='games' WHERE app='games';"
)

reverse_sql_query = (
    "UPDATE django_content_type SET app_label='games' WHERE app_label='games';"
    "ALTER TABLE games_wallet RENAME TO casino_wallet;"
    "ALTER TABLE games_vault RENAME TO casino_vault;"
    "UPDATE django_migrations SET app='games' WHERE app='games';"
)


class Migration(migrations.Migration):
    dependencies = []

    operations = [
        migrations.RunSQL(sql=sql_query, reverse_sql=reverse_sql_query),
    ]
