# Generated by Django 5.1.2 on 2025-04-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_alter_wallet_last_visit_alter_wallet_wallet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='last_visit',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='wallet_id',
            field=models.CharField(default='da09c33cdba84bf89f1a05b67484fbd1', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
