# Generated by Django 5.1.2 on 2024-11-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmingStats', '0002_crop_price_apr_crop_price_aug_crop_price_dec_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='name',
        ),
        migrations.AddField(
            model_name='crop',
            name='name_de',
            field=models.CharField(default='Crop', max_length=50),
        ),
        migrations.AddField(
            model_name='crop',
            name='name_eng',
            field=models.CharField(default='Crop', max_length=50),
        ),
        migrations.AddField(
            model_name='crop',
            name='name_yoda',
            field=models.CharField(default='Crop', max_length=50),
        ),
    ]
