# Generated by Django 5.1.2 on 2024-11-23 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmingStats', '0005_remove_crop_name_yoda'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='interval',
            field=models.IntegerField(default=0),
        ),
    ]
