# Generated by Django 5.1.2 on 2024-11-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmingStats', '0006_crop_interval'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crop',
            old_name='interval',
            new_name='harvest_interval',
        ),
        migrations.AddField(
            model_name='crop',
            name='planting_interval',
            field=models.IntegerField(default=0),
        ),
    ]
