# Generated by Django 4.2.3 on 2023-07-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_image_language_project_status_delete_router_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ('id',)},
        ),
        migrations.RemoveField(
            model_name='status',
            name='status_id',
        ),
        migrations.AlterField(
            model_name='status',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
