# Generated by Django 4.2.3 on 2023-07-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='D:\\Benutzer\\Documents\\GitHub\\timeofjustice.eu\\timeofjustice\\api/static/images/'),
        ),
    ]
