# Generated by Django 4.2.3 on 2023-07-19 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_image_options_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='data/images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='preview',
            field=models.ImageField(upload_to='data/images/'),
        ),
    ]
