# Generated by Django 4.2.3 on 2023-07-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_image_image_alter_image_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='C:/xampp/htdocs/timeofjustice.eu/timeofjustice/static/data/images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='preview',
            field=models.ImageField(upload_to='C:/xampp/htdocs/timeofjustice.eu/timeofjustice/static/data/images/'),
        ),
    ]
