# Generated by Django 4.2.3 on 2023-07-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_image_image_alter_image_preview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=100)),
            ],
        ),
    ]
