# Generated by Django 4.2.3 on 2023-07-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_cell_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
