# Generated by Django 4.2.3 on 2023-07-24 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_cell_last_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cell',
            old_name='last_updated',
            new_name='last_modified',
        ),
    ]
