# Generated by Django 4.2.3 on 2023-07-25 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_rename_last_updated_cell_last_modified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cell',
            options={'ordering': ('x', 'y')},
        ),
    ]
