# Generated by Django 4.2.3 on 2023-07-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_lastplaced_cell_placed_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceTimeOut',
            fields=[
                ('seconds', models.IntegerField(default=0, serialize=False)),
            ],
        ),
    ]
