# Generated by Django 4.2.3 on 2023-07-26 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_overlay_overlayimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='overlayimage',
            name='overlay',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.overlay'),
        ),
    ]
