# Generated by Django 4.2.3 on 2023-07-26 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_overlayimage_overlay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
