# Generated by Django 4.2.3 on 2023-07-28 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_overlayimage_convert'),
    ]

    operations = [
        migrations.AddField(
            model_name='overlayimage',
            name='max_colors',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
