# Generated by Django 4.2.3 on 2023-07-29 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_overlayimage_max_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='last_modified',
            field=models.DateTimeField(editable=False),
        ),
    ]
