# Generated by Django 4.2.3 on 2023-07-29 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_cell_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
