# Generated by Django 4.2.3 on 2023-07-30 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_alter_cell_id_alter_image_id_alter_overlay_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('last_updated', models.DateTimeField(default=datetime.datetime(2023, 7, 30, 14, 27, 41, 188563, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.AlterModelOptions(
            name='cell',
            options={'ordering': ('x', 'y'), 'verbose_name_plural': '2.0 Cells'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('index',), 'verbose_name_plural': '1.3 Images'},
        ),
        migrations.AlterModelOptions(
            name='lastplaced',
            options={'verbose_name_plural': '2.1 Last Placed'},
        ),
        migrations.AlterModelOptions(
            name='overlay',
            options={'verbose_name_plural': '2.3 Overlays'},
        ),
        migrations.AlterModelOptions(
            name='overlayimage',
            options={'verbose_name_plural': '2.4 Images'},
        ),
        migrations.AlterModelOptions(
            name='placetimeout',
            options={'verbose_name_plural': '2.2 Time-outs'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-name',), 'verbose_name_plural': '1.2 Projects'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ('id',), 'verbose_name_plural': '1.1 Status'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('name',), 'verbose_name_plural': '1.0 Tags'},
        ),
    ]
