# Generated by Django 4.2.3 on 2023-07-30 14:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_tiles_alter_cell_options_alter_image_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiles',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
