# Generated by Django 4.2.3 on 2023-07-30 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_alter_tiles_last_updated'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tiles',
            unique_together={('x', 'y')},
        ),
    ]
