# Generated by Django 4.2.3 on 2023-07-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_alter_tiles_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiles',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
