# Generated by Django 4.2.3 on 2023-07-30 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_tiles_delta_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiles',
            name='delta_update',
        ),
    ]
