# Generated by Django 4.2.3 on 2023-07-31 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_session_rename_tiles_tile_delete_lastplaced_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='overlay',
            options={'verbose_name': '  Overlay', 'verbose_name_plural': '  Overlays'},
        ),
        migrations.AlterModelOptions(
            name='overlayimage',
            options={'ordering': ('overlay', 'id'), 'verbose_name': '  Overlay-Image', 'verbose_name_plural': '  Overlay-Images'},
        ),
        migrations.AlterModelOptions(
            name='placetimeout',
            options={'verbose_name': '  Time-out', 'verbose_name_plural': '  Time-outs'},
        ),
        migrations.AlterField(
            model_name='overlay',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
