# Generated by Django 5.1.2 on 2025-08-20 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('page_color', models.CharField(default='#ffbaba', max_length=7)),
                ('background_color', models.CharField(default='#fff', max_length=7)),
                ('stamp_color', models.CharField(default='#e5b473', max_length=7)),
                ('accent_color', models.CharField(default='#e57373', max_length=7)),
                ('text_color', models.CharField(default='#333333', max_length=7)),
                ('icon', models.CharField(default='twemoji:teddy-bear', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Postcard',
            fields=[
                ('id', models.CharField(editable=False, max_length=6, primary_key=True, serialize=False)),
                ('message', models.TextField(default='Hallo, dies ist eine Postkarte')),
                ('greetings', models.CharField(default='Mit viel Liebe, dein Freund', max_length=255)),
                ('amount_reports', models.IntegerField(default=0)),
                ('showcased', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postcard.design')),
            ],
        ),
    ]
