# Generated by Django 5.1.2 on 2025-08-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postcard', '0002_alter_postcard_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcard',
            name='greetings',
            field=models.CharField(default='Mit viel Liebe, dein Freund', max_length=50),
        ),
    ]
