# Generated by Django 6.0 on 2025-12-30 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postcard', '0003_alter_postcard_greetings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='design',
            options={'ordering': ['id']},
        ),
    ]
