# Generated by Django 6.0 on 2026-01-02 16:19

import quiz.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.CharField(default=quiz.models.generate_session_id, editable=False, max_length=6, primary_key=True, serialize=False, unique=True)),
                ('host_id', models.CharField(default=quiz.models.generate_host_id, editable=False, max_length=8, unique=True)),
                ('max_players', models.PositiveIntegerField(default=4)),
                ('time_per_question', models.PositiveIntegerField(default=15)),
                ('mode', models.CharField(default='classic', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
