# Generated by Django 6.0 on 2026-01-09 19:10

import quiz.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='id',
            field=models.CharField(default=quiz.models.generate_player_id, editable=False, max_length=16, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.CharField(default=quiz.models.generate_session_id, editable=False, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
