# Generated by Django 6.0 on 2026-01-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_player_id_alter_session_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerGIF',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gif', models.FileField(upload_to='quiz/player_gifs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
