# Generated by Django 6.0 on 2026-01-09 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_playergif'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='gif',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='quiz.playergif'),
        ),
    ]
