# Generated by Django 5.1.2 on 2024-11-23 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farming_stats', '0007_rename_interval_crop_harvest_interval_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crop',
            options={'ordering': ['id']},
        ),
    ]
