# Generated by Django 5.1.2 on 2025-08-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farming_stats', '0009_commodity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='name_de',
            field=models.CharField(default='Ware', max_length=50),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='name_eng',
            field=models.CharField(default='Commodity', max_length=50),
        ),
        migrations.AlterField(
            model_name='crop',
            name='name_de',
            field=models.CharField(default='Frucht', max_length=50),
        ),
    ]
