# Generated by Django 6.0 on 2026-08-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_entry_value_alter_habit_goal_alter_habit_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='kind',
            field=models.CharField(choices=[('goal', 'Daily goal'), ('measure', 'Measurement over time')], default='goal', max_length=8),
        ),
    ]
