# Generated by Django 6.0 on 2026-08-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_habit_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='wide',
            field=models.BooleanField(default=False),
        ),
    ]
