# Generated by Django 6.0 on 2026-08-29 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0015_wallet_credentials"),
        ("habits", "0004_habit_wide"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_week", models.DateField()),
                (
                    "wallet",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habit_recap",
                        to="games.wallet",
                    ),
                ),
            ],
            options={
                "verbose_name": " Recap",
                "verbose_name_plural": " Recaps",
            },
        ),
    ]
