# Generated by Django 6.0 on 2026-08-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0005_recap"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="rest_days",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
