# Generated by Django 6.0 on 2026-08-29 14:59

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0006_habit_rest_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="goal_max",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.01")),
                    django.core.validators.MaxValueValidator(Decimal("1000000000")),
                ],
            ),
        ),
    ]
