# Generated by Django 5.1.2 on 2025-04-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_id',
            field=models.CharField(default='4e80692e31974c7e89b76e720edd6157', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
