# Generated by Django 5.1.2 on 2025-04-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_wallet_balance_alter_wallet_wallet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='name',
            field=models.CharField(default='Anonymous', max_length=32),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='wallet_id',
            field=models.CharField(default='2c1d6ad775a04f8293b4ed478f2e6a34', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
