# Generated by Django 5.1.2 on 2025-04-10 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0004_wallet_name_alter_wallet_wallet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='last_visit',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 10, 16, 36, 25, 458097)),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='wallet_id',
            field=models.CharField(default='ad683dffee8448948c8a7986d3740e1b', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
