# Generated by Django 5.1.2 on 2025-04-10 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_wallet_last_visit_alter_wallet_wallet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='last_visit',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 10, 14, 37, 36, 198070, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='wallet_id',
            field=models.CharField(default='155ce9ceb36c4a53b1343e058cef9fbd', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
