# Generated by Django 5.1.2 on 2025-04-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_alter_wallet_last_visit_alter_wallet_wallet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='last_visit',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='wallet_id',
            field=models.CharField(default='b53fbd99a52d47ddadbe714c0d7a2d2a', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
