# Generated by Django 5.1.2 on 2025-04-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_wallet_days_played_alter_wallet_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='last_visit',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='wallet_id',
            field=models.CharField(default='7db1c8b3ce314872b4251a5cb8319361', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
