# Generated by Django 5.1.2 on 2025-04-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_alter_wallet_wallet_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vault',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('balance', models.IntegerField(default=0)),
                ('last_redemption', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
