# Generated by Django 5.1.2 on 2025-04-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0012_vault'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='hint_dismissed',
            field=models.BooleanField(default=False),
        ),
    ]
