/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BAlert: typeof import('bootstrap-vue-next/components/BAlert')['BAlert']
    BAvatar: typeof import('bootstrap-vue-next/components/BAvatar')['BAvatar']
    BDropdown: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdown']
    BDropdownItem: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdownItem']
    BDropdownItemButton: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdownItemButton']
    BImg: typeof import('bootstrap-vue-next/components/BImg')['BImg']
    BOffcanvas: typeof import('bootstrap-vue-next/components/BOffcanvas')['BOffcanvas']
  }
}
