# Generated by Django 5.1.2 on 2024-10-29 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_project_github_alter_project_technology_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('german', models.TextField()),
                ('english', models.TextField()),
                ('yoda', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='technology',
            field=models.ManyToManyField(blank=True, to='core.technology'),
        ),
        migrations.AddField(
            model_name='image',
            name='alt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.text'),
        ),
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='short_description', to='core.text'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='description', to='core.text'),
        ),
    ]
