# Generated by Django 5.1.2 on 2024-10-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_project_short_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='files/images/project/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title_image',
            field=models.ImageField(upload_to='files/images/project/'),
        ),
    ]
