# Generated by Django 5.1.2 on 2024-10-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_image_image_alter_project_title_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title_image',
            field=models.ImageField(blank=True, null=True, upload_to='files/images/project/'),
        ),
    ]
