# Generated by Django 5.1.2 on 2024-10-30 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_status_color_alter_status_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='status',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
