# Generated by Django 5.1.2 on 2025-03-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_image_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('icon', models.ImageField(max_length=1000, upload_to='files/images/tool/')),
                ('alt', models.CharField(max_length=20)),
                ('url', models.URLField(max_length=100)),
            ],
        ),
    ]
