# Generated by Django 5.1.2 on 2025-03-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_tool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='alt',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='url',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
