# Generated by Django 5.1.2 on 2025-03-20 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_tool_alt_alter_tool_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='icon',
            field=models.FileField(max_length=1000, upload_to='files/images/tool/'),
        ),
    ]
