# Generated by Django 5.1.2 on 2025-03-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_tool_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=4)),
                ('text', models.TextField()),
            ],
            options={
                'unique_together': {('name', 'language')},
            },
        ),
    ]
