# Generated by Django 5.1.2 on 2025-03-20 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_profile_profile_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='profile_picture',
            new_name='picture',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='profile_short_description',
            new_name='short_description',
        ),
    ]
