# Generated by Django 5.1.2 on 2025-03-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_rename_profile_description_profile_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='translation',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='profile',
            name='repo',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
