# Generated by Django 5.1.2 on 2025-03-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_translation_options_profile_repo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='repo',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
