# Generated by Django 5.1.2 on 2025-03-22 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_image_alt_project_alt_project_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='alt_english',
        ),
        migrations.RemoveField(
            model_name='image',
            name='alt_german',
        ),
        migrations.RemoveField(
            model_name='image',
            name='alt_yoda',
        ),
        migrations.RemoveField(
            model_name='project',
            name='alt_english',
        ),
        migrations.RemoveField(
            model_name='project',
            name='alt_german',
        ),
        migrations.RemoveField(
            model_name='project',
            name='alt_yoda',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description_english',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description_german',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description_yoda',
        ),
        migrations.RemoveField(
            model_name='project',
            name='short_description_english',
        ),
        migrations.RemoveField(
            model_name='project',
            name='short_description_german',
        ),
        migrations.RemoveField(
            model_name='project',
            name='short_description_yoda',
        ),
        migrations.RemoveField(
            model_name='status',
            name='name_english',
        ),
        migrations.RemoveField(
            model_name='status',
            name='name_german',
        ),
        migrations.RemoveField(
            model_name='status',
            name='name_yoda',
        ),
    ]
