# Generated by Django 5.1.2 on 2025-03-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_image_alt_english_remove_image_alt_german_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='video',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to='files/video/project/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='files/images/project/'),
        ),
    ]
