name: Staging Deployment

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: self-hosted
    permissions:
      contents: read

    steps:
      - name: Check out current repository
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: |
          cd frontend/
          npm install

      - name: Get .env file
        run: |
          cd frontend/src/
          rsync -r /var/www/staging.timeofjustice.eu/.env .env

      - name: Vue Deploy
        run: |
          cd frontend/
          npm run build
    
  deploy:
    needs: build
    runs-on: self-hosted
    permissions:
      contents: read

    steps:
      - name: Copy config.ini
        run: |
          rsync -r /var/www/staging.timeofjustice.eu/config.ini config.ini

      - name: Create virtual environment
        run: |
          cd backend/
          python3.12 -m venv .env
          source .env/bin/activate
          pip3.12 install -r requirements.txt

      - name: Run Django migrations
        run: |
          cd backend/
          source .env/bin/activate
          python3.12 manage.py migrate

      - name: Collect static files
        run: |
          cd backend/
          source .env/bin/activate
          python3.12 manage.py collectstatic --noinput

      - name: Deploy
        run: |
          rsync -r --delete-delay backend/ /var/www/staging.timeofjustice.eu/backend/

      - name: Restart Django
        run: |
          touch /var/www/staging.timeofjustice.eu/backend/backend/wsgi.py
